/**
 * @license
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
package com.personallibrary.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

/**
 * Encapsulates an AI-synthesized document summary produced by Spring AI models
 * (such as Ollama Llama 3.3 or Mistral Large) including model metadata and performance metrics.
 *
 * @author Enterprise Architecture Team
 * @version 1.0.0
 * @since 2026-09-30
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SummaryRecord {
    /** The friendly model name (e.g. "Ollama Llama 3.3 (70B Instruct)"). */
    private String modelName;
    /** Model identifier key ("llama" or "mistral"). */
    private String modelKey;
    /** Markdown-formatted summary text generated by the model. */
    private String summaryText;
    /** Timestamp when the summary was generated. */
    private Instant createdAt;
    /** Formatted ISO string timestamp for client display. */
    private String timestamp;
    /** Inference duration in elapsed seconds. */
    private Double durationSeconds;
    /** User-friendly formatted duration string (e.g., "0 min 4.8 sec"). */
    private String durationFormatted;

    /**
     * Formats inference execution duration into readable minutes and seconds.
     *
     * WHAT: Decomposes total elapsed seconds into integral minutes and remaining fractional seconds with one decimal precision.
     * WHY: Provides user-friendly latency telemetry directly in the UI Object Page summary cards
     * so researchers understand LLM generation performance benchmarks.
     *
     * @param totalSeconds Elapsed time in seconds.
     * @return Formatted string representation (e.g. "1 min 14.2 sec").
     */
    public static String formatDuration(double totalSeconds) {
        long minutes = (long) (totalSeconds / 60);
        double seconds = totalSeconds % 60;
        return String.format("%d min %.1f sec", minutes, seconds);
    }
}

