#!/usr/bin/env bash
# =============================================================================
# Personal Library - clean rebuild & redeploy routine
#
# Wipes generated artifacts, rebuilds the frontend bundle, the Spring Boot JAR
# and the container image, then redeploys the full stack and verifies it.
#
# Data safety: persistent volumes are PRESERVED unless explicitly purged.
# The downloaded Ollama models (~7 GB) are kept even by --purge-data, because
# re-pulling them through a corporate TLS proxy is slow and failure prone;
# removing them requires the separate --purge-models opt-in.
#
# Doc safety: --deep only removes GENERATED documentation (docs/typescript,
# docs/javadoc, docs/diagrams — reproducible via `npm run docs`/`diagrams`).
# Hand-authored docs (architecture specs, presentations, openapi.yaml, the
# BPMN file, etc.) are never touched by this script; there is no npm task
# that can recreate them if deleted.
#
# Any destructive purge (--purge-data/--purge-models/--purge-all) requires an
# explicit, interactive 'yes' confirmation. Non-interactive shells (CI,
# scripted/agent invocations) MUST pass --force to proceed; there is no silent
# auto-skip of the confirmation.
#
# Usage: ./scripts/rebuild.sh [options]   (see --help)
# =============================================================================
set -Eeuo pipefail

readonly PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

# All compose invocations go through this wrapper so the central settings file
# and any personal overrides are always applied — a bare `docker compose` call
# would ignore both.
# shellcheck source=lib/compose-env.sh
source "${PROJECT_ROOT}/scripts/lib/compose-env.sh"
compose_env_args_into "$PROJECT_ROOT" COMPOSE_ENV_ARGS
dc() { docker compose "${COMPOSE_ENV_ARGS[@]}" "$@"; }

# Resolves one setting for the script's own output, mirroring Compose's
# precedence exactly: shell environment, then the personal dotenv, then the
# committed defaults, then the literal fallback.
#
# The files are deliberately NOT sourced wholesale. Exporting them would place
# every value in the shell environment, where Compose ranks it ABOVE the
# --env-file chain — silently defeating the personal overrides this is supposed
# to honour.
setting() {
  local key="${1:?key required}" fallback="${2-}" value line
  if [[ -n "${!key+x}" ]]; then
    printf '%s' "${!key}"; return
  fi
  for f in "${PROJECT_ROOT}/.env" "${PROJECT_ROOT}/config/settings.env"; do
    [[ -f "$f" ]] || continue
    line="$(grep -E "^[[:space:]]*${key}=" "$f" | tail -n 1 || true)"
    if [[ -n "$line" ]]; then
      value="${line#*=}"
      printf '%s' "$value"; return
    fi
  done
  printf '%s' "$fallback"
}

# --- Options ----------------------------------------------------------------
DEEP=false            # also drop node_modules and generated documentation
PURGE_DATA=false      # drop mongodb / qdrant / uploaded-file volumes
PURGE_MODELS=false    # drop the Ollama model cache as well
NO_CACHE=false        # build the image without the Docker layer cache
CLEAN_ONLY=false      # stop after the cleaning phase
SKIP_VERIFY=false     # skip the post-deploy verification phase
PULL=false            # refresh third-party base/service images
FORCE=false           # required alongside a purge flag in non-interactive shells

# Documentation generated by `npm run docs` / `npm run diagrams`; safe to wipe
# and fully reproducible. Everything else under docs/ (specs, presentations,
# openapi.yaml, the BPMN file, ...) is hand-authored source content and is
# NEVER deleted by this script.
readonly GENERATED_DOC_DIRS=(docs/typescript docs/javadoc docs/diagrams)

# docs/typescript and docs/javadoc are 100% generated. docs/diagrams is NOT: it
# mixes generated renditions with the hand-authored sources below, which no
# generator can recreate (architecture_diagrams.mmd is an *input* to
# generate-architecture-from-mmd.ts; the rest have no generator at all).
# Deleting the directory wholesale silently destroyed them, so they are skipped.
# Keep this list in sync when adding a hand-authored file under docs/diagrams/.
readonly PRESERVED_DIAGRAM_SOURCES=(
  docs/diagrams/MINDMAP.md
  docs/diagrams/architecture_diagrams.mmd
  docs/diagrams/rag_data_flow.drawio
  docs/diagrams/system_architecture.drawio
  docs/diagrams/system_architecture.puml
)

# Derived from the central configuration, so changing a port in
# config/settings.env keeps these checks (and the closing summary) pointing at
# the stack that was actually deployed.
readonly UI_PORT="$(setting APP_UI_PORT 13000)"
readonly BACKEND_PORT="$(setting APP_BACKEND_PORT 18080)"
readonly QDRANT_PORT="$(setting QDRANT_HTTP_PORT 16333)"

readonly UI_URL="http://localhost:${UI_PORT}/"
readonly API_URL="http://localhost:${BACKEND_PORT}/api/v1/documents"
readonly HEALTH_URL="http://localhost:${BACKEND_PORT}/actuator/health"

usage() {
  cat <<'USAGE'
Clean rebuild & redeploy for Personal Library.

Usage: ./scripts/rebuild.sh [options]

Cleaning scope
  --deep            Also remove node_modules/ and GENERATED documentation
                    (docs/typescript, docs/javadoc, docs/diagrams — reproducible
                    via 'npm run docs'/'diagrams'), forcing a dependency
                    reinstall and a documentation rebuild. Hand-authored docs
                    (specs, presentations, openapi.yaml, BPMN, ...) are never
                    touched: there is no npm task that can recreate them.
  --purge-data      Remove the MongoDB, Qdrant and uploaded-file volumes.
                    DESTROYS all stored documents. Ollama models are kept.
  --purge-models    Also remove the Ollama model cache (~7 GB re-download).
  --purge-all       Shorthand for --deep --purge-data --purge-models.
                    THIS IS A FACTORY RESET: all stored documents, vectors,
                    and models are destroyed. Use deliberately, never by habit.

Safety
  --force           Required, in addition to --purge-data/--purge-models/
                    --purge-all, when running non-interactively (no TTY on
                    stdin, e.g. CI or a scripted/agent invocation). There is
                    no silent auto-skip of the confirmation prompt: without
                    --force a non-interactive purge aborts.

Build & deploy
  --no-cache        Build the image without the Docker layer cache.
  --pull            Pull newer base and third-party service images.
  --clean-only      Clean, then stop (no build, no deploy).
  --skip-verify     Do not run the post-deploy verification.

  -h, --help        Show this help.

Always removed: dist/, target/, server.js, and the project's containers/image.
Always kept unless purged: MongoDB data, Qdrant vectors, uploaded files, models.
Never removed by this script: hand-authored docs/ content (non-generated).

Examples
  ./scripts/rebuild.sh                     # routine clean rebuild + redeploy
  ./scripts/rebuild.sh --deep --no-cache   # fully reproducible rebuild
  ./scripts/rebuild.sh --purge-all         # factory reset (re-pulls models)
  ./scripts/rebuild.sh --purge-all --force # same, for non-interactive/CI use
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --deep)          DEEP=true ;;
    --purge-data)    PURGE_DATA=true ;;
    --purge-models)  PURGE_MODELS=true ;;
    --purge-all)     DEEP=true; PURGE_DATA=true; PURGE_MODELS=true ;;
    --force)         FORCE=true ;;
    --no-cache)      NO_CACHE=true ;;
    --pull)          PULL=true ;;
    --clean-only)    CLEAN_ONLY=true ;;
    --skip-verify)   SKIP_VERIFY=true ;;
    -h|--help)       usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; echo >&2; usage >&2; exit 2 ;;
  esac
  shift
done

# --- Output helpers ---------------------------------------------------------
if [[ -t 1 ]]; then
  C_RESET=$'\033[0m'; C_BOLD=$'\033[1m'; C_DIM=$'\033[2m'
  C_RED=$'\033[31m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_BLUE=$'\033[34m'
else
  C_RESET=''; C_BOLD=''; C_DIM=''; C_RED=''; C_GREEN=''; C_YELLOW=''; C_BLUE=''
fi

STEP=0
step() { STEP=$((STEP + 1)); printf '\n%s==> [%d] %s%s\n' "$C_BOLD$C_BLUE" "$STEP" "$1" "$C_RESET"; }
info() { printf '    %s\n' "$1"; }
note() { printf '    %s%s%s\n' "$C_DIM" "$1" "$C_RESET"; }
ok()   { printf '    %s✓%s %s\n' "$C_GREEN" "$C_RESET" "$1"; }
warn() { printf '    %s!%s %s\n' "$C_YELLOW" "$C_RESET" "$1"; }
fail() { printf '\n%s✗ %s%s\n' "$C_RED$C_BOLD" "$1" "$C_RESET" >&2; exit 1; }

trap 'fail "Rebuild aborted at step ${STEP} (line ${LINENO})."' ERR

readonly START_TS=$SECONDS

# --- Phase 1: preflight -----------------------------------------------------
step "Preflight checks"
command -v docker >/dev/null 2>&1 || fail "docker is required but not installed."
docker compose version >/dev/null 2>&1 || fail "the 'docker compose' plugin is required."
docker info >/dev/null 2>&1 || fail "the Docker daemon is not reachable. Is it running?"
ok "Docker $(docker version --format '{{.Server.Version}}') and Compose $(docker compose version --short)"

# config/settings.env is the single place to change any stack setting, but
# docker-compose.yml also carries matching `${VAR:-default}` fallbacks so a bare
# `docker compose up` still works. If those two ever disagree, editing the
# central file would silently do nothing for anyone not using these scripts.
if ! "${PROJECT_ROOT}/scripts/check-config.sh"; then
  fail "Configuration drift detected. Reconcile config/settings.env with docker-compose.yml."
fi

# Containers inherit the Docker daemon's DNS resolver, not the host's. When
# /etc/docker/daemon.json pins a public resolver the local network degrades or
# blocks, model pulls fail with "server misbehaving" — yet the host resolves
# names perfectly, so the cause is rarely obvious. The failure is typically
# *intermittent* (a measured ~1-in-6 lookup failure rate on this network),
# which is fatal across the many lookups a multi-gigabyte pull performs, and
# leaves the stack running with no models. The backend then dies at startup,
# because the Qdrant store probes the embedding model for its dimensions.
#
# A connectivity probe is useless here precisely because the fault is
# intermittent: it usually passes, then the pull dies anyway. Instead compare
# the daemon's pinned resolver against the host's own. If the daemon sends
# container DNS somewhere the host itself does not use, prefer the host's
# resolver — it demonstrably works, since the rest of this build depends on it.
if [[ -z "$(setting LIBRARY_DNS)" ]]; then
  host_dns="$(awk '/^nameserver/ {print $2; exit}' /etc/resolv.conf 2>/dev/null || true)"
  daemon_dns=""
  if [[ -r /etc/docker/daemon.json ]]; then
    daemon_dns="$(tr -d ' \n' < /etc/docker/daemon.json 2>/dev/null \
      | sed -n 's/.*"dns":\[\([^]]*\)\].*/\1/p' | tr -d '"' || true)"
  fi
  if [[ -n "$host_dns" && -n "$daemon_dns" && ",${daemon_dns}," != *",${host_dns},"* ]]; then
    export LIBRARY_DNS="$host_dns"
    warn "Docker pins container DNS to '${daemon_dns}', which the host itself does not use."
    note "Using the host resolver ${host_dns} for Ollama and the seeder this run."
    note "Persist it so plain 'docker compose up' works too — set this in"
    note "  config/settings.env:  LIBRARY_DNS=${host_dns}"
  fi
fi

if $PURGE_DATA || $PURGE_MODELS; then
  targets=""
  $PURGE_DATA   && targets="documents, vectors and uploaded files"
  $PURGE_MODELS && targets="${targets:+$targets plus }the Ollama model cache (~7 GB re-download)"
  warn "This will permanently delete ${targets}."
  if [[ -t 0 ]]; then
    read -r -p "    Type 'yes' to continue: " confirm
    [[ "$confirm" == "yes" ]] || fail "Aborted by user."
  elif $FORCE; then
    warn "Non-interactive shell with --force: proceeding without a typed confirmation."
  else
    fail "Non-interactive shell detected and no confirmation is possible. Re-run with --force to confirm this destructive purge explicitly."
  fi
fi

# --- Phase 2: clean ---------------------------------------------------------
step "Removing the running stack"
# --remove-orphans also clears containers left behind by earlier compose files.
compose_down=(dc down --remove-orphans)
if $PURGE_DATA && $PURGE_MODELS; then
  compose_down+=(--volumes)
fi
"${compose_down[@]}"
ok "Containers and network removed."

if $PURGE_DATA && ! $PURGE_MODELS; then
  # Selective purge: drop the data volumes but keep the expensive model cache.
  for volume in personal-library-mongodb-data personal-library-qdrant-data personal-library-file-storage; do
    if docker volume inspect "$volume" >/dev/null 2>&1; then
      docker volume rm "$volume" >/dev/null
      ok "Volume '$volume' removed."
    fi
  done
  note "Ollama model cache preserved (use --purge-models to drop it)."
elif $PURGE_MODELS && ! $PURGE_DATA; then
  if docker volume inspect personal-library-ollama-models >/dev/null 2>&1; then
    docker volume rm personal-library-ollama-models >/dev/null
    ok "Ollama model cache removed; models will be re-pulled on start."
  fi
elif ! $PURGE_DATA; then
  note "Persistent volumes kept (documents, vectors, files, models)."
fi

step "Deleting build artifacts"

# `docker compose build` compiles as root inside the container. If target/ (or
# dist/) was ever produced by a root-owned process that wrote back to the host,
# the files end up owned by root:root and a plain host-side `rm -rf` fails with
# "Permission denied" — aborting the whole reset. Rather than demanding `sudo`
# (which the rest of this script never needs), delete such leftovers the same
# way they were created: from a throwaway root container. Docker is already a
# verified preflight dependency, so this introduces no new requirement.
remove_artifact() {
  local artifact="$1"
  if rm -rf -- "${PROJECT_ROOT:?}/$artifact" 2>/dev/null; then
    ok "Removed $artifact"
    return 0
  fi
  note "Host-side delete of $artifact was denied; retrying as root in a container."
  # Only the parent is mounted and only this basename is removed, so a bad
  # value cannot escape the project root.
  if docker run --rm \
       -v "${PROJECT_ROOT:?}:/work" \
       -w /work \
       alpine:3.20 \
       rm -rf -- "./$artifact" >/dev/null 2>&1; then
    ok "Removed $artifact (via container, was root-owned)"
    return 0
  fi
  fail "Could not remove '$artifact' even as root. Remove it manually and re-run."
}

artifacts=(dist target server.js)
# Only ever delete the specific generated-doc subdirectories, never docs/
# itself — docs/ also holds hand-authored specs, presentations, openapi.yaml,
# and the BPMN file that no npm task can recreate.
$DEEP && artifacts+=("${GENERATED_DOC_DIRS[@]}" node_modules)

# Stash the hand-authored sources that live inside docs/diagrams/ so the
# directory delete below cannot destroy them, then put them back afterwards.
preserve_stash=""
if $DEEP; then
  preserve_stash="$(mktemp -d)"
  for src in "${PRESERVED_DIAGRAM_SOURCES[@]}"; do
    if [[ -f "$src" ]]; then
      mkdir -p "$preserve_stash/$(dirname "$src")"
      cp -p -- "$src" "$preserve_stash/$src"
    fi
  done
fi

for artifact in "${artifacts[@]}"; do
  if [[ -e "$artifact" ]]; then
    remove_artifact "$artifact"
  else
    note "Skipped $artifact (absent)"
  fi
done

if $DEEP; then
  restored=0
  for src in "${PRESERVED_DIAGRAM_SOURCES[@]}"; do
    if [[ -f "$preserve_stash/$src" ]]; then
      mkdir -p "$(dirname "$src")"
      cp -p -- "$preserve_stash/$src" "$src"
      restored=$((restored + 1))
    fi
  done
  rm -rf -- "$preserve_stash"
  (( restored > 0 )) && ok "Preserved $restored hand-authored diagram source(s) in docs/diagrams/."
  note "Hand-authored docs/ content preserved (specs, presentations, openapi.yaml, BPMN, ...)."
fi

# Drop the application image so the next build cannot silently reuse it.
app_image="$(dc config --images 2>/dev/null | grep -- '-personal-library-app$' || true)"
if [[ -n "$app_image" ]] && docker image inspect "$app_image" >/dev/null 2>&1; then
  docker image rm -f "$app_image" >/dev/null
  ok "Application image '$app_image' removed."
fi

if $CLEAN_ONLY; then
  printf '\n%s✓ Clean complete in %ds. Build and deploy skipped (--clean-only).%s\n' \
    "$C_GREEN$C_BOLD" "$((SECONDS - START_TS))" "$C_RESET"
  if $DEEP; then
    # --deep removed node_modules and the committed generated-doc trees, and
    # --clean-only exits before the phases that would rebuild them. Say so
    # explicitly: otherwise the next `git status` shows ~200 deleted files with
    # no obvious cause.
    warn "--deep also removed node_modules and the generated documentation."
    info "Restore them with:"
    info "    npm ci && npm run docs && npm run diagrams"
  fi
  exit 0
fi

# --- Phase 3: host-side quality gate ----------------------------------------
# Catching type errors here is far cheaper than failing inside a Docker layer.
step "Type-checking the frontend"
if command -v npm >/dev/null 2>&1; then
  if [[ ! -d node_modules ]]; then
    info "Installing dependencies (npm ci)..."
    npm_flags=()
    # Some workstations enforce a machine-wide npm policy that blocks remote
    # fetches. Relax it for this invocation only; project config is untouched.
    [[ "$(npm config get allow-remote 2>/dev/null)" == "none" ]] && npm_flags+=(--allow-remote=all)
    if ! npm ci "${npm_flags[@]}"; then
      warn "npm ci failed on the host; the Docker build will install its own copy."
    fi
  fi
  if [[ -d node_modules ]]; then
    npm run --silent lint || fail "Type-check failed. Fix the errors above and re-run."
    ok "tsc --noEmit reported no errors."
  fi
else
  warn "npm not found on the host; relying on the in-container build."
fi

# --- Phase 3b: regenerate the documentation --deep just deleted -------------
# Without this, a --deep run leaves ~200 tracked files missing from git and the
# next `git status` is a wall of spurious deletions. These dirs are committed
# artifacts, so the reset is only truly reversible once they are rebuilt.
if $DEEP && [[ -d node_modules ]]; then
  step "Regenerating API documentation and diagrams"
  if npm run --silent docs >/dev/null 2>&1; then
    ok "Regenerated docs/typescript and docs/javadoc."
  else
    warn "npm run docs failed; regenerate manually before committing."
  fi
  if npm run --silent diagrams >/dev/null 2>&1; then
    ok "Regenerated docs/diagrams."
  else
    warn "npm run diagrams failed; regenerate manually before committing."
  fi
  info "Review with 'git status docs/' — regenerated output may legitimately differ."
fi

# --- Phase 4: build ---------------------------------------------------------
step "Building the container image (frontend bundle + Spring Boot JAR)"
build_cmd=(dc build)
$NO_CACHE && build_cmd+=(--no-cache)
$PULL     && build_cmd+=(--pull)
"${build_cmd[@]}" || fail "Image build failed."
ok "Image built."

# --- Phase 5: deploy --------------------------------------------------------
step "Deploying the stack"
# `--wait` blocks until every service with a healthcheck reports healthy, so a
# failure here means a service genuinely did not come up.
#
# Caveat: `--wait` also fails when *any* waited container exits — including a
# one-shot job that completed successfully with exit code 0. `library-seeder`
# is exactly such a job (it uploads the starter documents and terminates), so
# waiting on it turns every successful deployment into a reported failure.
# It is therefore excluded from the waited set and started separately below.
# Plain `docker compose up` is unaffected and still seeds as documented.
readonly ONESHOT_SERVICES=("library-seeder")
wait_services=()
while IFS= read -r svc; do
  for oneshot in "${ONESHOT_SERVICES[@]}"; do
    [[ "$svc" == "$oneshot" ]] && continue 2
  done
  wait_services+=("$svc")
done < <(dc config --services)

up_cmd=(dc up -d --wait)
$PULL && up_cmd+=(--pull always)
up_cmd+=("${wait_services[@]}")
if ! "${up_cmd[@]}"; then
  warn "Services did not all become healthy. Recent application logs:"
  dc logs --tail=40 personal-library-app || true
  fail "Deployment failed."
fi
ok "All services report healthy."

# Starter-document seeding runs after the stack is confirmed healthy. It is
# intentionally non-fatal: a failed seed (no network, CDN unreachable) must not
# fail an otherwise good deployment.
if ! dc up -d --no-deps library-seeder >/dev/null 2>&1; then
  warn "Could not start library-seeder; starter documents may be missing."
else
  note "Starter-document seeding started (see: docker compose logs library-seeder)."
fi
dc ps --format 'table {{.Service}}\t{{.Status}}'

# --- Phase 6: verify --------------------------------------------------------
if $SKIP_VERIFY; then
  note "Post-deploy verification skipped (--skip-verify)."
else
  step "Verifying the deployment"

  check_http() {
    local label="$1" url="$2" code
    code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$url" || echo 000)"
    if [[ "$code" == "200" ]]; then
      ok "$label → HTTP 200"
    else
      warn "$label → HTTP $code (expected 200)"
      return 1
    fi
  }

  verify_failed=false
  check_http "Frontend (UI)          " "$UI_URL"     || verify_failed=true
  check_http "Spring Boot health     " "$HEALTH_URL" || verify_failed=true
  check_http "Documents API          " "$API_URL"    || verify_failed=true

  # The AI features are unusable without the language and embedding models.
  models="$(dc exec -T ollama ollama list 2>/dev/null | tail -n +2 | awk '{print $1}' | paste -sd' ' - || true)"
  if [[ -n "$models" ]]; then
    ok "Ollama models ready: $models"
  else
    warn "No Ollama models present yet; they may still be downloading."
    note "Follow progress: docker compose logs -f ollama | grep ollama-entrypoint"
  fi

  # A healthy stack is NOT evidence of a working one. Indexing failures in
  # VectorRagService are caught and logged at WARN while uploads still return
  # 200, so documents can appear in the UI with zero embeddings behind them —
  # RAG then silently answers from the model's own training data instead of the
  # library. The only honest check is asking Qdrant how many vectors it holds.
  vector_status="$(curl -s --max-time 20 \
    "http://localhost:${QDRANT_PORT}/collections/personal_library_embeddings" 2>/dev/null || true)"
  if [[ -z "$vector_status" ]]; then
    warn "Qdrant did not respond; vector search is unavailable."
  elif grep -q '"status":"ok"' <<<"$vector_status"; then
    points="$(sed -n 's/.*"points_count":\([0-9]*\).*/\1/p' <<<"$vector_status")"
    if [[ "${points:-0}" -gt 0 ]]; then
      ok "Qdrant vectors indexed: ${points} point(s)."
    else
      note "Qdrant collection exists but holds 0 vectors (expected on a fresh"
      note "  purge until seeding/upload completes; otherwise indexing is failing:"
      note "  docker compose logs personal-library-app | grep -i 'vector\\|qdrant'"
    fi
  else
    warn "Qdrant collection 'personal_library_embeddings' is missing."
    note "It is created at startup by 'initialize-schema: true'. Without it, every"
    note "  index call fails and RAG answers are ungrounded."
  fi

  $verify_failed && fail "Deployment verification failed; see the warnings above."
fi

printf '\n%s✓ Clean rebuild and deploy completed in %ds.%s\n' \
  "$C_GREEN$C_BOLD" "$((SECONDS - START_TS))" "$C_RESET"
printf '    UI          %s\n' "$UI_URL"
printf '    Spring Boot %s\n' "http://localhost:${BACKEND_PORT}/api/v1"
printf '    Logs        %s\n' "docker compose logs -f personal-library-app"
