/**
 * @license
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Domain model definitions for the Personal Library Application.
 * Includes BibTeX schemas, dual-model summary structures, document chunks for RAG,
 * user authentication profiles, and search filter specifications.
 * @packageDocumentation
 */

/**
 * Standard BibTeX entry classification types.
 */
export type BibTeXType = 'article' | 'book' | 'inproceedings' | 'techreport' | 'phdthesis' | 'misc';

/**
 * Structured BibTeX bibliographic metadata attributes extracted from documents
 * or supplied during ingestion.
 */
export interface BibTeXMetadata {
  /** The standard entry category (e.g., article, book, techreport) */
  entryType: BibTeXType;
  /** Unique BibTeX citation key identifier */
  bibKey: string;
  /** Primary document or book title */
  title: string;
  /** Author list (comma or 'and' separated) */
  author: string;
  /** Publication year */
  year: string;
  /** Publication month (optional) */
  month?: string;
  /** Journal title for academic articles */
  journal?: string;
  /** Conference proceedings or book collection title */
  booktitle?: string;
  /** Journal volume number */
  volume?: string;
  /** Journal issue or report number */
  number?: string;
  /** Page range or count */
  pages?: string;
  /** Publishing house or distributor */
  publisher?: string;
  /** Edition specification (e.g., '1st', '2nd Revised') */
  edition?: string;
  /** Sponsoring institution for technical reports */
  institution?: string;
  /** University or academic department for theses */
  school?: string;
  /** Digital Object Identifier (DOI) */
  doi?: string;
  /** Canonical URL link to the document source */
  url?: string;
  /** Comprehensive executive abstract */
  abstract?: string;
  /** Comma-delimited topical keywords and tags */
  keywords?: string;
}

/**
 * Model execution summary output generated by Spring AI Ollama models.
 */
export interface SummaryRecord {
  /** Descriptive model name (e.g., 'Ollama Llama 3.3 (70B Instruct)') */
  modelName: string;
  /** Unique key identifying the model engine ('llama' | 'mistral') */
  modelKey: 'llama' | 'mistral';
  /** Synthesized summary text in markdown format */
  summaryText: string;
  /** ISO-8601 creation timestamp */
  createdAt: string;
  /** Optional legacy timestamp alias */
  timestamp?: string;
  /** Elapsed inference time in seconds */
  durationSeconds: number;
  /** Human-readable elapsed inference duration (e.g., '4.8s' or '1m 12s') */
  durationFormatted: string;
}

/**
 * Text passage chunk with vector embedding mapping for RAG search.
 */
export interface DocumentChunk {
  /** Unique chunk identifier */
  id: string;
  /** Zero-based chunk order index */
  chunkIndex: number;
  /** Text content of the passage chunk */
  text: string;
}

/**
 * Core enterprise document record representing an ingested asset with
 * bibliographic metadata, multi-model summaries, and vector index fragments.
 */
export interface DocumentRecord {
  /** Unique document identifier (UUID v4) */
  guid: string;
  /** Pointer to predecessor document GUID if versioned */
  previousVersionGuid: string | null;
  /** Active revision sequence number */
  versionNumber: number;
  /** Original file name with extension */
  fileName: string;
  /** File size in bytes */
  fileSize: number;
  /** Formatted file size string (e.g., '2.4 MB') */
  fileSizeFormatted: string;
  /** Canonical file format extension (pdf, docx, txt, md, etc.) */
  format: string;
  /** ISO-8601 upload timestamp */
  uploadDate: string;
  /** ISO-8601 latest edit/overwrite timestamp */
  editDate: string;
  /** Structured bibliographic metadata */
  bibtex: BibTeXMetadata;
  /** Raw standard BibTeX entry formatted string */
  bibtexRaw: string;
  /** Dual-model synthesized executive and analytical summaries */
  summaries: {
    llama?: SummaryRecord;
    mistral?: SummaryRecord;
  };
  /** Short initial text excerpt for list previews */
  contentExcerpt: string;
  /** Complete extracted text content for search and vectorization */
  fullContent?: string;
  /** Segmented document chunks for Qdrant vector retrieval */
  chunks: DocumentChunk[];
}

/**
 * Authenticated user profile decoded from Keycloak OpenID Connect JWT tokens.
 */
export interface UserProfile {
  /** Keycloak user UUID */
  id: string;
  /** System login account username */
  username: string;
  /** Verified primary email address */
  email: string;
  /** Display name */
  name: string;
  /** Realm and client assigned RBAC roles */
  roles: string[];
  /** Keycloak tenant realm name */
  realm: string;
  /** ISO-8601 authentication session timestamp */
  authenticatedAt: string;
}

/**
 * Filter state parameters applied in the SAP Horizon List Report floorplan.
 */
export interface FilterState {
  /** Partial match on physical file name */
  fileName: string;
  /** Partial match on bibliographic title */
  title: string;
  /** Partial match on author name */
  author: string;
  /** Exact or partial match on edition */
  edition: string;
  /** Target format filter ('all' or specific extension like 'pdf') */
  format: string;
  /** Full-text search query across content and chunk passages */
  content: string;
}

/**
 * Conversation message exchanged within the document RAG assistant panel.
 */
export interface ChatMessage {
  /** Unique message identifier */
  id: string;
  /** Role of the message participant */
  role: 'user' | 'assistant';
  /** Message content in markdown */
  text: string;
  /** ISO-8601 transmission timestamp */
  timestamp: string;
  /** Optional citations and vector chunks retrieved to substantiate the response */
  citations?: {
    chunkIndex: number;
    score: number;
    snippet: string;
  }[];
}
